//! `josephine report` — a plain-text, dated snapshot of the machine's health,
//! printed to stdout or written to a file for archiving.

use std::path::PathBuf;

use anyhow::{Context, Result};
use chrono::Local;
use josephine_core::check::{CheckResult, Severity};
use josephine_core::config::Config;
use josephine_core::i18n::{self, Lang};
use josephine_core::scheduler::run_all_checks;

use crate::output::{check_label, format_metric_value, primary_metric, print_checks_json};

pub fn run(output: Option<PathBuf>, json: bool) -> Result<()> {
    let config = Config::load_default()?;
    let results = run_all_checks(&config)?;

    // `--json` always prints to stdout; `--output` is a rendered-text-only
    // concern and is ignored when `--json` is set.
    if json {
        print_checks_json(&results);
        return Ok(());
    }

    let generated = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
    let report = render_report(&results, &generated, &hostname());

    match output {
        Some(path) => {
            std::fs::write(&path, &report)
                .with_context(|| format!("writing {}", path.display()))?;
            let done = path.display();
            println!(
                "{}",
                match i18n::lang() {
                    Lang::En => format!("Report saved to {done}."),
                    Lang::Fr => format!("Rapport enregistré dans {done}."),
                }
            );
        }
        None => print!("{report}"),
    }
    Ok(())
}

fn render_report(results: &[CheckResult], generated: &str, host: &str) -> String {
    let global = results
        .iter()
        .map(CheckResult::worst_severity)
        .max()
        .unwrap_or(Severity::Info);

    let mut out = String::new();
    out.push_str(i18n::t(
        "Joséphine — system report\n",
        "Joséphine — rapport système\n",
    ));
    out.push_str(&format!("{:<12}: {generated}\n", i18n::t("Date", "Date")));
    out.push_str(&format!("{:<12}: {host}\n", i18n::t("Machine", "Machine")));
    out.push_str(&format!(
        "{:<12}: {}\n",
        i18n::t("Global state", "État global"),
        state_label(global)
    ));
    out.push_str(&"=".repeat(60));
    out.push('\n');

    for result in results {
        let severity = result.worst_severity();
        let value = result
            .status_value
            .clone()
            .or_else(|| primary_metric(result).map(format_metric_value))
            .unwrap_or_else(|| "—".to_string());

        out.push_str(&format!(
            "\n[{}] {} — {}\n",
            state_label(severity),
            check_label(&result.check_name),
            value
        ));
        for detail in &result.details {
            out.push_str(&format!("    {}\n", detail.trim()));
        }
    }

    out.push_str("\n------------------------------------------------------------\n");
    out.push_str(i18n::t(
        "Generated by Joséphine · 100% local\n",
        "Généré par Joséphine · 100 % local\n",
    ));
    out
}

fn state_label(severity: Severity) -> &'static str {
    match severity {
        Severity::Info => "OK      ",
        Severity::Attention => i18n::t("WARNING ", "ATTENTION"),
        Severity::Critique => i18n::t("CRITICAL", "CRITIQUE "),
    }
}

fn hostname() -> String {
    std::fs::read_to_string("/proc/sys/kernel/hostname")
        .map(|s| s.trim().to_string())
        .ok()
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "machine".to_string())
}
